In [1]:
ls

 磁碟區 C 中的磁碟是 Windows
 磁碟區序號:  FE49-3B7A

 C:\Users\wind84128\dm\TKU-DM-610530601 的目錄

2022/09/29  上午 10:21    <DIR>          .
2022/09/29  上午 10:21    <DIR>          ..
2022/09/29  上午 10:19    <DIR>          .ipynb_checkpoints
2022/09/22  上午 11:14             8,575 0915-1.ipynb
2022/09/22  上午 11:41             7,410 0922.ipynb
2022/09/29  上午 10:21               589 0929.ipynb
2022/09/22  上午 11:07                18 README.md
2022/09/22  上午 11:39           152,261 scores.csv
               5 個檔案         168,853 位元組
               3 個目錄  15,969,599,488 位元組可用


In [3]:
%%writefile hi.py    #寫檔案
print("hi 0929!")

Writing hi.py


In [4]:
run hi.py

hi 0929!


In [7]:
a = 1    #b快捷，加新cell

In [6]:
b = 2

In [8]:
whos

Variable   Type    Data/Info
----------------------------
a          int     1
b          int     2


In [10]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

In [12]:
np1 = np.array([1,2,3,4])
np2 = np.array((5,6,7,8))
print(np1)
print(np2)
print(type(np1), type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [13]:
print(np1)
print(np2)
print(type(np1), type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [14]:
np3 = np.arange(0, 31, 2)

In [15]:
np3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [24]:
np4 = np.linspace(1, 15, 5)

In [25]:
np4

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [27]:
np5 = np.zeros((5,))

In [34]:
np5

array([0., 0., 0., 0., 0.])

In [35]:
np6 = np.ones((5,))

In [36]:
np6

array([1., 1., 1., 1., 1.])

In [39]:
np7 = np.ones((5,3))

In [40]:
np7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
listdata = [[1,2,3,4,5],
           [6,7,8,9,10]]
np8 = np.array(listdata)

In [43]:
listdata

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [45]:
np8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
print("維度", np8.ndim)
print("形狀", np8.shape)
print("數量", np8.size)

維度 2
形狀 (2, 5)
數量 10


In [47]:
np9 = np.arange(1, 21)
print(np9)
np10 = np9.reshape(4, 5)    #數量要相同
print(np10)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [48]:
#取一維資料
np10 =np.arange(0, 9)
print(np10)
print(np10[0])
print(np10[8])
print(np10[1:8])
print(np10[1:8:2])
print(np10[8:1:-1])
print(np10[:])
print(np10[4:])
print(np10[:4])

[0 1 2 3 4 5 6 7 8]
0
8
[1 2 3 4 5 6 7]
[1 3 5 7]
[8 7 6 5 4 3 2]
[0 1 2 3 4 5 6 7 8]
[4 5 6 7 8]
[0 1 2 3]


In [54]:
#取二維陣列資料

np11 = np.arange(1, 21).reshape(5, 4)
print(np11,"\n")
print(np11[0, 2],"\n")
print(np11[1, 2],"\n")
print(np11[0][2],"\n")
print(np11[1:3, 2],"\n")
print(np11[1:3, 1:3],"\n")
print(np11[::2, ::2],"\n")
print(np11[:, 2],"\n")
print(np11[1, :],"\n")
print(np11[:, :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] 

3 

7 

3 

[ 7 11] 

[[ 6  7]
 [10 11]] 

[[ 1  3]
 [ 9 11]
 [17 19]] 

[ 3  7 11 15 19] 

[5 6 7 8] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [55]:
np12 = np.genfromtxt('scores.csv', delimiter=',', skip_header=1)

In [56]:
np12

array([[ 1., 87., 85., 82.],
       [ 2., 92., 87., 90.],
       [ 3., 80., 91., 87.],
       [ 4., 78., 82., 95.],
       [ 5., 88., 89., 90.],
       [ 6., 82., 87., 88.],
       [ 7., 90., 92., 82.],
       [ 8., 87., 80., 90.],
       [ 9., 95., 78., 87.],
       [10., 90., 88., 95.],
       [11., 88., 89., 75.],
       [12., 82., 91., 66.],
       [13., 90., 82., 87.],
       [14., 87., 89., 92.],
       [15., 95., 87., 80.],
       [16., 90., 92., 78.],
       [17., 82., 80., 88.],
       [18., 90., 78., 93.],
       [19., 67., 87., 95.],
       [20., 91., 82., 88.],
       [21., 82., 81., 82.],
       [22., 79., 87., 90.],
       [23., 87., 92., 87.],
       [24., 92., 82., 95.],
       [25., 80., 90., 78.],
       [26., 78., 76., 91.],
       [27., 66., 90., 82.],
       [28., 89., 77., 89.],
       [29., 87., 95., 87.],
       [30., 73., 90., 92.]])

In [57]:
np13 = np.genfromtxt('2317.TW.csv', delimiter=',', skip_header=1)

In [58]:
np13

array([[          nan, 1.1412500e+02, 1.1475000e+02, ..., 1.1437500e+02,
        9.3712265e+01, 2.3687200e+07],
       [          nan, 1.1350000e+02, 1.1437500e+02, ..., 1.1437500e+02,
        9.3712265e+01, 1.9390400e+07],
       [          nan, 1.1462500e+02, 1.1462500e+02, ..., 1.1412500e+02,
        9.3507431e+01, 1.3385600e+07],
       ...,
       [          nan, 1.0150000e+02, 1.0250000e+02, ..., 1.0150000e+02,
        1.0150000e+02, 3.5941142e+07],
       [          nan, 1.0350000e+02, 1.0450000e+02, ..., 1.0400000e+02,
        1.0400000e+02, 4.3536754e+07],
       [          nan, 1.0500000e+02, 1.0600000e+02, ..., 1.0600000e+02,
        1.0600000e+02, 8.2056684e+07]])

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install scipy


     ---------------------------------------- 39.8/39.8 MB 1.3 MB/s eta 0:00:00


In [13]:
import scipy.stats as st
import numpy as np

EU_AM = 'EUROPEAN'
c_p = str(input("CALL or PUT:"))

S0: float = 16000       # 期初股價
K: float = 16000        # 履約價
T: float = 3 / 12       # 年化到期時間
r: float = 0.012        # 無風險利率
vol: float = 0.16       # 波動度
q: float = 0.036        # 股利率


def BSM_pricing(K: float):    
    d1 = (np.log(S0 / K) + ((r - q) + vol ** 2 / 2) * T) / (vol * (T ** 0.5))
    d2 = (np.log(S0 / K) + ((r - q) - vol ** 2 / 2) * T) / (vol * (T ** 0.5))
    call_p = S0 * np.exp(-q * T) * st.norm.cdf(d1) - K * np.exp(-r * T) * st.norm.cdf(d2)
    put_p  = K * np.exp(-r * T) * st.norm.cdf(-d2) - S0 * np.exp(-q * T) * st.norm.cdf(-d1)
    if c_p == 'CALL':
        return max(call_p, 0)
    elif c_p == 'PUT':
        return max(put_p, 0)
    else:
        raise ValueError('Wrong c_p.')
        
BSM_P = BSM_pricing(K)
print('Black-Scholes-Merton [EUROPEAN CALL] 選擇權價格 = %1.4f' % BSM_P)

CALL or PUT:CALL
Black-Scholes-Merton [EUROPEAN CALL] 選擇權價格 = 461.1712


In [11]:
a = 20 #全域變數
def F():
    a = 5  #區域變數
    b = 10
    c = a + b
    return(c)
print(F())
print(a)

15
20
